import type { AppLanguage } from '../../core/i18n/language';

const copy = {
  en: {
    title: 'Workflows',
    subtitle: 'Build and run local multi-agent DAGs',
    goal: 'Workflow goal',
    goalPlaceholder: 'Describe the outcome, constraints, and verification...',
    generate: 'Generate draft',
    newWorkflow: 'New workflow',
    empty: 'No workflows yet',
    emptyBody: 'Create a blank workflow or generate an editable draft.',
    updated: 'Updated',
    nodes: 'nodes',
    editor: 'Workflow editor',
    back: 'Back to workflows',
    save: 'Save',
    saving: 'Saving',
    validate: 'Validate',
    valid: 'DAG is valid',
    invalid: 'Resolve graph issues before running',
    run: 'Run',
    palette: 'Nodes',
    inspector: 'Inspector',
    settings: 'Workflow settings',
    maxConcurrency: 'Maximum concurrency',
    defaultTimeout: 'Default timeout (seconds)',
    defaultRetries: 'Default retries',
    noSelection: 'Select a node to edit its properties.',
    name: 'Name',
    provider: 'Provider',
    prompt: 'Prompt',
    timeout: 'Timeout (seconds)',
    retries: 'Retries',
    auto: 'Automatic',
    autoLayout: 'Auto layout',
    undo: 'Undo',
    redo: 'Redo',
    duplicate: 'Duplicate node',
    delete: 'Delete node',
    add: 'Add',
    runTitle: 'Workflow run',
    runSummary: 'Runtime status and integration evidence',
    integration: 'Integration branch',
    approvals: 'Approvals',
    log: 'Run log',
    attempt: 'Attempt',
    waiting: 'Waiting for approval',
    approve: 'Approve worktree creation',
    cancel: 'Cancel run',
  },
  'zh-CN': {
    title: '工作流',
    subtitle: '构建并运行本地多 Agent DAG',
    goal: '工作流目标',
    goalPlaceholder: '描述目标、约束和验证方式...',
    generate: '生成草案',
    newWorkflow: '新建工作流',
    empty: '暂无工作流',
    emptyBody: '新建空白工作流，或根据自然语言生成可编辑草案。',
    updated: '更新于',
    nodes: '个节点',
    editor: '工作流编辑器',
    back: '返回工作流',
    save: '保存',
    saving: '保存中',
    validate: '验证',
    valid: 'DAG 验证通过',
    invalid: '请先解决图中的问题再运行',
    run: '运行',
    palette: '节点',
    inspector: '属性检查器',
    settings: '工作流设置',
    maxConcurrency: '最大并发数',
    defaultTimeout: '默认超时（秒）',
    defaultRetries: '默认重试次数',
    noSelection: '选择节点以编辑属性。',
    name: '名称',
    provider: 'Provider',
    prompt: '提示词',
    timeout: '超时（秒）',
    retries: '重试次数',
    auto: '自动',
    autoLayout: '自动布局',
    undo: '撤销',
    redo: '重做',
    duplicate: '复制节点',
    delete: '删除节点',
    add: '添加',
    runTitle: '工作流运行',
    runSummary: '运行状态与集成证据',
    integration: '集成分支',
    approvals: '审批',
    log: '运行日志',
    attempt: '尝试次数',
    waiting: '等待审批',
    approve: '批准创建 worktree',
    cancel: '取消运行',
  },
} as const;

export function workflowCopy(language: AppLanguage) {
  return copy[language];
}
